version: '3.8'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    # platform: linux/amd64
    restart: always
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      # - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "xpack.security.enabled=false"
      - cluster.initial_master_nodes=es01,es02
      - discovery.seed_hosts=es02,es03,es04
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    restart: always
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      # - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "xpack.security.enabled=false"
      - cluster.initial_master_nodes=es01,es02
      - discovery.seed_hosts=es01,es04,es03
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
      - 9301:9300
    networks:
      - esnet
    depends_on:
      - es01
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    restart: always
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      # - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "xpack.security.enabled=false"
      - cluster.initial_master_nodes=es01,es02
      - discovery.seed_hosts=es01,es02,es04
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    ports:
      - 9202:9200
      - 9302:9300
    networks:
      - esnet
    depends_on:
      - es01
      - es02
  es04:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    restart: always
    container_name: es04
    environment:
      - node.name=es04
      - cluster.name=es-docker-cluster
      # - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - "xpack.security.enabled=false"
      - cluster.initial_master_nodes=es01,es02
      - discovery.seed_hosts=es01,es02,es03
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data04:/usr/share/elasticsearch/data
    ports:
      - 9203:9200
      - 9303:9300
    networks:
      - esnet
    depends_on:
      - es01
      - es02
      - es03

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    restart: always
    # platform: linux/amd64
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      # ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - esnet
    depends_on:
      - es01
      - es02
      - es03
      - es04

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local
  data04:
    driver: local

networks:
  esnet:
    driver: bridge
