version: '3.8'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    # platform: linux/amd64
    restart: always
    container_name: es01
    environment:
      - node.name=es01
      # - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - test

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    restart: always
    # platform: linux/amd64
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - test

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  test:
    name: testname