version: '3.7'

services:
  mysql-5:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'dongju'
      TZ: 'Asia/Seoul'
      MYSQL_USER: 'dongju'
      MYSQL_PASS: 'dongju'
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d